branch-defaults:
  main:
    environment: simple-chat-app-dev
    group_suffix: null
environment-defaults:
  simple-chat-app-dev:
    branch: null
    repository: null
global:
  application_name: simple-chat-app
  branch: main
  default_ec2_keyname: aws-eb
  default_platform: Corretto 11 running on 64bit Amazon Linux 2
  default_region: ap-northeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: simple-chat-app
  sc: git
  workspace_type: Application
